// authReducer
export const SUCCESS_AUTH = "SUCCESS_AUTH"
// consoleReducer
export const FULL_SCREEN_TOGGLE = "FULL_SCREEN_TOGGLE"
export const CHECK_REQUEST = "CHECK_REQUEST"
export const INSERT_REQUEST = "INSERT_REQUEST"
export const FORMAT_REQUEST = "FORMAT_REQUEST"
export const INSERT_ANSWER = "INSERT_ANSWER"
// historyReducer
export const ADD_REQUEST_HISTORY = "ADD_REQUEST_HISTORY"
export const ADD_ALL_REQUEST_HISTORY = "ADD_ALL_REQUEST_HISTORY"
export const REMOVE_HISTORY = "REMOVE_HISTORY"
export const REMOVE_HISTORY_ITEM = "REMOVE_HISTORY_ITEM"
